<?php

// Your user data array. Keep the formatting the same but change the users to be loaded as needed.
$users = [
    [
        'id' => '2',
        'username' => 'abriggs',
        'name' => 'Aimee Wall',
        'first_name' => 'Aimee',
        'last_name' => 'Wall',
        'email' => 'wall@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/aimee-n-wall',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Aimee-Wall.jpg',
    ],
    [
        'id' => '7',
        'username' => 'bcliff',
        'name' => 'David Lawrence',
        'first_name' => 'David',
        'last_name' => 'Lawrence',
        'email' => 'lawrence@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/david-m-lawrence',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/David-M.-Lawrence.jpg',
    ],
    [
        'id' => '',
        'username' => 'bcummins',
        'name' => 'Bradley Cummins',
        'first_name' => 'Bradley',
        'last_name' => 'Cummins',
        'email' => 'cummins@sog.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '16',
        'username' => 'botts',
        'name' => 'Mark Botts',
        'first_name' => 'Mark',
        'last_name' => 'Botts',
        'email' => 'botts@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/mark-f-botts',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Mark-Botts.jpg',
    ],
    [
        'id' => '26',
        'username' => 'becky36',
        'name' => 'Rebecca Badgett',
        'first_name' => 'Rebecca',
        'last_name' => 'Badgett',
        'email' => 'rbadgett@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'caindi',
        'name' => 'India Simpson',
        'first_name' => 'India',
        'last_name' => 'Simpson',
        'email' => 'caindi@live.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'campbell',
        'name' => 'Jim Campbell',
        'first_name' => 'Jim',
        'last_name' => 'Campbell',
        'email' => 'campbell@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '6',
        'username' => 'cbmclaug',
        'name' => 'Chris McLaughlin',
        'first_name' => 'Chris',
        'last_name' => 'McLaughlin',
        'email' => 'McLaughlin@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/christopher-b-mclaughlin',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/mclaughlin_2021_head_shot.jpg',
    ],
    [
        'id' => '23',
        'username' => 'ccrews',
        'name' => 'Connor Crews',
        'first_name' => 'Connor',
        'last_name' => 'Crews',
        'email' => 'ccrews@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/connor-crews',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Connor-Crews.jpg',
    ],
    [
        'id' => '',
        'username' => 'cheyjoli',
        'name' => 'Cheyenne Desrosiers',
        'first_name' => 'Cheyenne',
        'last_name' => 'Desrosiers',
        'email' => 'cheyjoli@live.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'crowellm',
        'name' => 'Michael Crowell',
        'first_name' => 'Michael',
        'last_name' => 'Crowell',
        'email' => 'crowellm@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/michael-crowell',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Michael-Crowell.jpg',
    ],
    [
        'id' => '9',
        'username' => 'ctmullig',
        'name' => 'Tyler Mulligan',
        'first_name' => 'Tyler',
        'last_name' => 'Mulligan',
        'email' => 'mulligan@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/c-tyler-mulligan',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Tyler-Mulligan.jpg',
    ],
    [
        'id' => '11',
        'username' => 'dwowens',
        'name' => 'David Owens',
        'first_name' => 'David',
        'last_name' => 'Owens',
        'email' => 'owens@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/david-w-owens',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/David-Owens.jpg',
    ],
    [
        'id' => '4',
        'username' => 'eyouens',
        'name' => 'Eileen R Youens',
        'first_name' => 'Eileen',
        'last_name' => 'Youens',
        'email' => 'eyouens@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => '',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Eileen-R.-Youens.png',
    ],
    [
        'id' => '12',
        'username' => 'fbell2',
        'name' => 'Fleming Bell',
        'first_name' => 'Fleming',
        'last_name' => 'Bell',
        'email' => 'bell@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/fleming-bell-ii',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Fleming-Bell.jpg',
    ],
    [
        'id' => '5',
        'username' => 'frayda',
        'name' => 'Frayda Bluestein',
        'first_name' => 'Frayda',
        'last_name' => 'Bluestein',
        'email' => 'bluestein@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/frayda-s-bluestein',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Frayda-Bluestein.jpg',
    ],
    [
        'id' => '',
        'username' => 'gaallen',
        'name' => 'Georgia Allen',
        'first_name' => 'Georgia',
        'last_name' => 'Allen',
        'email' => 'allen@sog.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'Guest Blogger',
        'name' => 'Guest Blogger',
        'first_name' => 'Guest',
        'last_name' => 'Blogger',
        'email' => 'blogmaster@sog.unc.edu',
        'role' => 'Contributor',
        'author_bio_url' => '',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Guest.png',
    ],
    [
        'id' => '',
        'username' => 'jag',
        'name' => 'John Gullo',
        'first_name' => 'John',
        'last_name' => 'Gullo',
        'email' => 'johngullo@hotmail.com',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '22',
        'username' => 'jill-jd',
        'name' => 'Jill Moore',
        'first_name' => 'Jill',
        'last_name' => 'Moore',
        'email' => 'moore@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/jill-d-moore',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Jill-Moore.jpg',
    ],
    [
        'id' => '27',
        'username' => 'jjoyce',
        'name' => 'Jim Joyce',
        'first_name' => 'Jim',
        'last_name' => 'Joyce',
        'email' => 'jljoyce@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/james-jim-joyce',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Jim-Joyce.jpg',
    ],
    [
        'id' => '20',
        'username' => 'jmmarkha',
        'name' => 'James Markham',
        'first_name' => 'James',
        'last_name' => 'Markham',
        'email' => 'markham@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/james-m-markham',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/James-Markham.jpg',
    ],
    [
        'id' => '18',
        'username' => 'juffras',
        'name' => 'Diane Juffras',
        'first_name' => 'Diane',
        'last_name' => 'Juffras',
        'email' => 'juffras@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/diane-m-juffras',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Diane-Juffras.jpg',
    ],
    [
        'id' => '24',
        'username' => 'knickodem',
        'name' => 'Kristi Nickodem',
        'first_name' => 'Kristi',
        'last_name' => 'Nickodem',
        'email' => 'nickodem@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/kristi-nickodem',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Nickodem_Kristi_2',
    ],
    [
        'id' => '',
        'username' => 'blankkwilson',
        'name' => 'Kristina Wilson',
        'first_name' => 'Kristina',
        'last_name' => 'Wilson',
        'email' => 'wilson@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/kristina-wilson',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Wilson_Kristina_2021_153_web.jpg',
    ],
    [
        'id' => '',
        'username' => 'lhoyt',
        'name' => 'Lindsay Hoyt',
        'first_name' => 'Lindsay',
        'last_name' => 'Hoyt',
        'email' => 'hoyt@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '17',
        'username' => 'lovelady',
        'name' => 'Adam Lovelady',
        'first_name' => 'Adam',
        'last_name' => 'Lovelady',
        'email' => 'adamlovelady@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/adam-lovelady',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Lovelady_Adam_2016_8488-web.jpg',
    ],
    [
        'id' => '',
        'username' => 'margaretH',
        'name' => 'Margaret Henderson',
        'first_name' => 'Margaret',
        'last_name' => 'Henderson',
        'email' => 'margaret@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/margaret-f-henderson',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Margaret-Henderson.jpg',
    ],
    [
        'id' => '',
        'username' => 'mckirahan',
        'name' => 'Matthew McKirahan',
        'first_name' => 'Matthew',
        'last_name' => 'McKirahan',
        'email' => 'mckirahan@sog.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'mkadel',
        'name' => 'Max Kadel',
        'first_name' => 'Max',
        'last_name' => 'Kadel',
        'email' => 'mkadel@sog.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'nmills',
        'name' => 'Norma Houston',
        'first_name' => 'Norma',
        'last_name' => 'Houston',
        'email' => 'nhouston@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/norma-r-houston',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Norma-Houston.jpg',
    ],
    [
        'id' => '13',
        'username' => 'oleg',
        'name' => 'Oleg',
        'first_name' => 'Oleg',
        'last_name' => '',
        'email' => 'odrozd@live.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'panke',
        'name' => 'Stefanie Panke',
        'first_name' => 'Stefanie',
        'last_name' => 'Panke',
        'email' => 'panke@sog.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'rebeccab',
        'name' => 'Rebecca Badgett',
        'first_name' => 'Rebecca',
        'last_name' => 'Badgett',
        'email' => 'rbadgett@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/rebecca-badgett',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Rebecca-Badgett.jpg',
    ],
    [
        'id' => '8',
        'username' => 'riducker',
        'name' => 'Richard Ducker',
        'first_name' => 'Richard',
        'last_name' => 'Ducker',
        'email' => 'ducker@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/richard-d-ducker',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Richard-Ducker.jpg',
    ],
    [
        'id' => '32',
        'username' => 'rjoyce',
        'name' => 'Robert Joyce',
        'first_name' => 'Robert',
        'last_name' => 'Joyce',
        'email' => 'joyce@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/robert-p-joyce',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Robert-Joyce.jpg',
    ],
    [
        'id' => '',
        'username' => 'romoore',
        'name' => 'Rob Moore',
        'first_name' => 'Rob',
        'last_name' => 'Moore',
        'email' => 'robmoore@sog.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '3',
        'username' => 'rowing',
        'name' => 'Kara Millonzi',
        'first_name' => 'Kara',
        'last_name' => 'Millonzi',
        'email' => 'Millonzi@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/kara-millonzi',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Kara-Millonzi.jpg',
    ],
    [
        'id' => '21',
        'username' => 'sarad513',
        'name' => 'Sara DePasquale',
        'first_name' => 'Sara',
        'last_name' => 'DePasquale',
        'email' => 'sara@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/sara-depasquale',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Sara-DePasquale.jpg',
    ],
    [
        'id' => '10',
        'username' => 'sdenning',
        'name' => 'Shea Denning',
        'first_name' => 'Shea',
        'last_name' => 'Denning',
        'email' => 'denning@sog.unc.edu',
        'role' => 'Contributor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/shea-riggsbee-denning',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Shea-Denning.jpg',
    ],
    [
        'id' => '1',
        'username' => 'SOGCANONT8B4',
        'name' => 'SOG Apps',
        'first_name' => 'SOG',
        'last_name' => 'Applications',
        'email' => 'blogs@sog.unc.edu',
        'role' => 'administrator',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'stephen_brooks',
        'name' => 'Stephen Brooks',
        'first_name' => 'Stephen',
        'last_name' => 'Brooks',
        'email' => 'stephen_brooks@unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'sungsong',
        'name' => 'Sung Song',
        'first_name' => 'Sung',
        'last_name' => 'Song',
        'email' => 'sungsong@live.unc.edu',
        'role' => 'none',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '',
        'username' => 'szota',
        'name' => 'Sejal Zota',
        'first_name' => 'sejal',
        'last_name' => 'Zota',
        'email' => 'szota@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => '',
        'author_photo' => '',
    ],
    [
        'id' => '14',
        'username' => 'szypszak',
        'name' => 'Chuck Szypszak',
        'first_name' => 'Chuck',
        'last_name' => 'Szypszak',
        'email' => 'szypszak@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/charles-szypszak',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Charles-Szypszak.jpg',
    ],
    [
        'id' => '19',
        'username' => 'tallen',
        'name' => 'Trey Allen',
        'first_name' => 'Trey',
        'last_name' => 'Allen',
        'email' => 'tallen@sog.unc.edu',
        'role' => 'editor',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/trey-allen',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Todd-Allen.jpg',
    ],
    [
        'id' => '',
        'username' => 'welty',
        'name' => 'Jeff Welty',
        'first_name' => 'Jeff',
        'last_name' => 'Welty',
        'email' => 'welty@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/jeffrey-b-welty',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Welty_Jeffrey_2022_web.jpg',
    ],
    [
        'id' => '',
        'username' => 'rfisher',
        'name' => 'Rebecca Fisher-Gabbard',
        'first_name' => 'Rebecca',
        'last_name' => 'Fisher-Gabbard',
        'email' => 'rfisher@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/rebecca-l-fisher-gabbard',
        'author_photo' => '/wp-content/uploads/sites/1175/2024/06/R.-Fisher-Gabbard.png',
    ],
    [
        'id' => '',
        'username' => 'kirsten',
        'name' => 'Kirsten Leloudis',
        'first_name' => 'Kirsten',
        'last_name' => 'Leloudis',
        'email' => 'kirsten@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/kirsten-leloudis',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Leloudis_Kirsten_web.jpg',
    ],
    [
        'id' => '',
        'username' => 'kvantol',
        'name' => 'Kathryn Val Tol',
        'first_name' => 'Kathryn',
        'last_name' => 'Val Tol',
        'email' => 'kvantol@sog.unc.edu',
        'role' => 'author',
        'author_bio_url' => 'https://www.sog.unc.edu/about/faculty-and-staff/kathryn-van-tol',
        'author_photo' => '/wp-content/uploads/sites/1175/2015/12/Guest.png',
    ],
];

return $users;
